//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traincore.Connection
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrainEntities2 : DbContext
    {
        public TrainEntities2()
            : base("name=TrainEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Marshrut> Marshrut { get; set; }
        public virtual DbSet<Passangers> Passangers { get; set; }
        public virtual DbSet<Schedule> Schedule { get; set; }
        public virtual DbSet<Seats> Seats { get; set; }
        public virtual DbSet<Stations> Stations { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tickets> Tickets { get; set; }
        public virtual DbSet<Trains> Trains { get; set; }
        public virtual DbSet<Type_Trains> Type_Trains { get; set; }
        public virtual DbSet<Type_Wagons> Type_Wagons { get; set; }
        public virtual DbSet<Wagons> Wagons { get; set; }
    }
}
