//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traincore.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Schedule()
        {
            this.Tickets = new HashSet<Tickets>();
        }
    
        public int ID_Schedule { get; set; }
        public int ID_Train { get; set; }
        public int ID_Route { get; set; }
        public System.DateTime Date_Start { get; set; }
        public System.TimeSpan Time_start { get; set; }
        public System.DateTime Date_finish { get; set; }
        public System.TimeSpan Time_finish { get; set; }
    
        public virtual Marshrut Marshrut { get; set; }
        public virtual Trains Trains { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tickets> Tickets { get; set; }
    }
}
