//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traincore.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int ID_Ticket { get; set; }
        public int ID_Passanger { get; set; }
        public int ID_Seat { get; set; }
        public int ID_Schedule { get; set; }
        public Nullable<System.DateTime> Date_buy { get; set; }
        public decimal Stoimost { get; set; }
    
        public virtual Passangers Passangers { get; set; }
        public virtual Schedule Schedule { get; set; }
        public virtual Seats Seats { get; set; }
    }
}
