//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traincore.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wagons
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Wagons()
        {
            this.Seats = new HashSet<Seats>();
        }
    
        public int ID_Wagon { get; set; }
        public int ID_Train { get; set; }
        public int ID_type_wagon { get; set; }
        public string Number_wagon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seats> Seats { get; set; }
        public virtual Trains Trains { get; set; }
        public virtual Type_Wagons Type_Wagons { get; set; }
    }
}
